config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :weblinks do
    member do
      patch 'favorite'
      patch 'unfavorite'
    end
  end
  root to: 'users#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/mylinks' => 'weblinks#index'
  get '/addlinks' => 'weblinks#new'
  post '/weblinks' => 'weblinks#create'
  get '/weblinks' => 'weblinks#show'
  delete '/destroy' => 'weblinks#destroy'
  get '/myfavorites' => 'weblinks#favorites'
  patch '/weblinks/:id/edit(.:format)' => 'weblinks#edit'

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  has_many :links
  has_secure_password
  before_save { self.url = url.downcase } 
  # URL_REGEX = /(http:\/\/www.)|\w+\.+\w+?\.\w+/i

  validates :url, presence: true, uniqueness: true,
            # format:     { with: URL_REGEX },
            uniqueness: { case_sensitive: false }   

  validates :username, :presence => true, :uniqueness => true, :length => {:in => 5..15}
  validates :email, :presence => true, :uniqueness => true

end

app/models/weblink.rb
class Weblink < ActiveRecord::Base
  belongs_to :user
  before_save { self.url = url.downcase } 
  # URL_REGEX = /(http:\/\/www.)|\w+\.+\w+?\.\w+/i

  validates :url, presence: true, uniqueness: true,
            # format:     { with: URL_REGEX },
            uniqueness: { case_sensitive: false }   

  def favorited?
    !favorite.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  # def authorize
  #   redirect_to 'login' unless current_user
  # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create #when the user signs in .aka. login
    # binding.pry
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/', :notice => "Welcome back, #{user.email}"
    else
      redirect_to '/login', :notice => "Log In Unsuccessful"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

  # def authenticate(encrypted_password)
  #   if @user.password == encrypted_password

  # end

  # def password
  #   @password ||= Password.new(password_hash)
  # end
  # def password=(new_password)
  #   @password = BCrypt::Password.create(new_password)
  #   self.password_hash = @password
  # end

  # def login
  #   @user = User.find_by_email(params[:email])
  #   if @user.password == params[:password]
  #     give_token
  #   else
  #     # redirect_to 'user#new'
  #   end
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_filter :authorize
  def index
  # binding.pry
  end

  def new
    @user = User.new
  end

  def create #creating an account
    params.permit!
    @user = User.new(params[:user])
    if @user.errors.any? # If there are errors, do something
      @user.errors.each do |attribute, message|
        message
      end
    end

    @user.save

    if @user.save
      flash[:notice] = "You Signed up successfully"
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
      flash[:notice] = @user.errors.full_messages.first
    end
    # render "new"
  end
 

  def show
  end

  def update
  end

  private

  def user_params
    params.require(:user).permit(:id, :name, :email, :username, :password, :password_confirmation)
  end

end

app/controllers/weblinks_controller.rb
class WeblinksController < ApplicationController

  def index
    # binding.pry
    @weblinks = Weblink.where(:user_id => session[:user_id])

  end

  def show
    require 'pismo'
    @url_id = Weblink.all.find(params[:id])
    @doc = Pismo::Document.new(@url_id.url)
    # @img_best = MetaInspector.new(@url_id.url)
  end

  def new
    @weblinks = Weblink.new
  end

  def edit
    @weblinks = Weblink.all.find(params[:id])
  end

  def update
    @weblinks = Weblink.all.find(params[:id])
    # @weblinks.find(params[:id])
    @weblinks.update(weblink_params)
    redirect_to '/mylinks' 
  end

  def destroy
    @link = Weblink.all.find(params[:id])
    @link.destroy
    redirect_to '/mylinks'
  end

  def create
    params.permit!
    @weblinks = Weblink.new(params[:weblink])
    # @weblinks = Weblinks.find(params[:links])
    # @weblinks_user = Weblinks.find(params[:user_id])
    @weblinks.save

    if @weblinks.save
      flash[:notice] = "Added Link Successfully"
      redirect_to '/mylinks'
    else
      flash[:notice] = @weblinks.errors.full_messages.first
      # flash[:notice] = "Link Addition Unsuccessful"
      redirect_to '/addlinks'
    end
  end
  # def toggle_favorite?
  #   toggle!(:favorite) if favorite.blank? 

  # end
  def favorites
    # @weblink = Weblink.all.find(params[:id])
    # binding.pry
    @fav_links = Weblink.where(:favorite => true)
  end

  def favorite
    @weblink = Weblink.all.find(params[:id])
    @weblink.update_attribute(:favorite, true)
    flash[:notice] = "Favorited Link Successfully"
    redirect_to '/mylinks'
  end

  def unfavorite
    @weblink = Weblink.all.find(params[:id])
    @weblink.update_attribute(:favorite, false)
    flash[:notice] = "Unfavorited Link Successfully"
    redirect_to '/mylinks'
  end

  private

  def weblink_params
    params.require(:weblink).permit(:user_id, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/weblinks_helper.rb
module WeblinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PocketClone</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>
<body>

<div class="rainbow-bars1"></div>
<div class="rainbow-bars2"></div>
<div class="rainbow-bars3"></div>
<div class="rainbow-bars4"></div>


<!-- <nav><img href="../../assets/images/pocket-logo.png"/></nav> -->

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1><%#= link_to 'Sign In Please', new_user_path(@user) %></h1>
<h1>Users#index</h1>

<% if current_user %>
<% notice %>
You are signed in <%= current_user.name %> | <%= link_to 'Logout', '/logout' %><br>


<%= link_to 'Add links', '/addlinks' %><br>
<%= link_to 'My favorite links', '/myfavorites' %><br>
<%= link_to 'My links', '/mylinks' %>


<% else %> 
<h4><%#= link_to 'Sign Up Please', new_user_path(@user) %></h4>
<%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
<% end %>


<%# if current_user %>
<!-- <p>Welcome</p><%# @user.name %> -->
<%#= link_to "Sign out", "/signout"%>

<!-- <h3><%#= notice %></h3><br> -->
<!-- <p>you are signed in</p> -->
<%# end %>

app/views/users/new.html.erb
<%# if !current_user %>
<h3><%= notice %></h3><br>

<!-- <p>Sign Up Here</p><br> -->
<img src="https://ununsplash.imgix.net/photo-1433650552684-d4004a945d6c?dpr=1.5&amp;fit=crop&amp;fm=jpg&amp;h=725&amp;q=75&amp;w=1075" alt="Photo By Thomas Lefebvre" data-width="4800" data-height="3109" style="height: 864px; position:fixed; background-size: 80px 60px;
    background-repeat: no-repeat;">

<h1 style="position:fixed; margin-left: 650px; margin-top: 95px;">Sign Up Here | <%= link_to 'Login', '/login' %> </h1>
<form class="form-horizontal">
<%= form_for @user do |f| %>
  <%# if @user.errors.any? %>
  <!-- <p>Error:</p> -->
    <%# @user.errors.full_messages.each do |message| %>
    <%#= message %>

      <%#= pluralize(@user.errors.count, "error")%>
    <%# end %>

    <%# if @user.errors.full_messages.any? %>
<%# @user.errors.full_messages.each do |error_message| %>
<%#= error_message %> <br />
<%# end %>
<%# end %>
    <%# end %>
    <div class="form-group">
    <div class="col-sm-10", style="padding-left: 700px;padding-top: 134px; ">
  <%= f.label 'Name'  %>
  <%= f.text_field :name%>

    </div>
  </div>  

  <div class="form-group">
    <div class="col-sm-10", style="padding-left: 700px;padding-top: 20px; ">
  <%= f.label 'Email'  %>
  <%= f.text_field :email %>

    </div>
  </div>  

  <div class="form-group">
    <div class="col-sm-10", style="padding-left: 700px;padding-top: 20px; ">
  <%= f.label 'Username'  %>
  <%= f.text_field :username %>

    </div>
  </div>  

  <div class="form-group">
    <div class="col-sm-10", style="padding-left: 700px;padding-top: 20px; ">
  <%= f.label 'Password'  %>
  <%= f.password_field :password  %>

    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-10", style="padding-left: 700px;padding-top: 20px; ">
  <%= f.label 'Password Confirmation'  %>
  <%= f.password_field :password_confirmation  %>

    </div>
  </div>
    <div style='position:fixed; margin-left: 710px; margin-top:12px;'><%= f.submit 'SUBMIT'%></div>
  
<% end%>
</form>

<%#= link_to 'Login', '/login' %> 

app/views/weblinks/_addlinks.html.erb
<%= form_for @weblinks do |f| %>
<% if @weblinks.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@weblinks.errors.count, "error") %> prohibited this weblinks from being saved:</h2>
 
    <ul>
    <% @weblinks.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit "Add link" %>
<% end %><br>

app/views/weblinks/_form.html.erb
<%= form_for @weblinks do |f| %>
  <%= f.label :url %>
  <%= f.text_field :url %>
<%= f.submit "Update" %>
<% end %>

app/views/weblinks/edit.html.erb
<h4> Edit your Link </h4>
<%= render 'form' %>

<%= link_to 'Back', '/mylinks' %><br>

app/views/weblinks/favorites.html.erb
All favorites

<% @fav_links.each do |fav| %>
  <% if fav.favorited? %>
   <h5><a href="http://www.<%= fav.url %>"><%= fav.url %></a></h5>
    <%= link_to unfavorite_weblink_path(fav), method: :patch do %>
      <i style="opacity: 0.4;" class="fa fa-heart"></i>
    <% end %>
  <% end %>
<% end %><br>


<%= link_to 'My links', '/mylinks' %><br>
<%= link_to 'Home', '/' %><br>

app/views/weblinks/index.html.erb
<nav>
  <!-- <img href="../../assets/images/pocket-logo.png"/> -->
  <im2g src="http://i.imgur.com/tpOIcII.png?1" title="source: imgur.com" />
<div class="current"><h5 class="fixplease"><%= current_user.name %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Logout', '/logout' %></h5></div>
</nav>


<!--==================================-->
<div class="sidenav">
      <!-- <div class="mylist">My List</h5> -->

  <%#= render 'addlinks', locals: { weblinks: @weblinks }%><br>
  <div class="myfavorite"><%= link_to 'Favorites', '/myfavorites' %><br></div>
  <div class="addlinks"><%= link_to 'Add links', '/addlinks' %><br></div>
  <div class="home"><%= link_to 'Home', '/' %><br></div>

  <div class="line"></div>

  <div class="archives"><%= link_to 'Archives', '/' %><br></div>
</div>

<!--==================================-->
    <h5 class="list-type">My List</h5>

<div class="container">
<!-- <h1>Weblinks#index</h1> -->
<!-- <p>Find me in app/views/weblinks/index.html.erb</p> -->

  <%= notice %>

  <% @weblinks.each do |link| %>
      <%#binding.pry%>
      <% @img_best = MetaInspector.new("#{link.url}") %>
      <% @webpage = Pismo::Document.new("#{link.url}") %>

  <!-- <div class="link-container"> -->
  <ul>
    <li>
      <img class="li-images" src="<%= @img_best.images.best%>">
      <% if @img_best.images.best%>
        <img class="li-images"<% @img_best.images.best %> />
      <% else %>
        <img class="li-images" src="../../assets/images/non-picture-pocket.jpg" />
      <% end %>


      <h5 class="link-title"><a href=""><%= @webpage.title %></a>
      <!-- <div class="restful-links"> -->
      <div class="hover-links">
      <%= link_to "Show", weblink_path(link), :method => :get %>
        <!-- <h5><a href="http://www.<%#= link.url %>"><%#= link.url %></a></h5> -->
      <% if link.favorited? %>
        <%#= link_to favorite_weblink_path(link), method: :patch do %>
        <!--   <i style="opacity: 0.4;" class="fa fa-heart"></i> -->
            <%= link_to unfavorite_weblink_path(link), method: :patch do %>
              <i style="opacity: 0.4;" class="fa fa-heart"></i>
            <% end %>
        <%# end %>
      <% else %>
     
        <%= link_to favorite_weblink_path(link), method: :patch do %>
          <i class="fa fa-heart-o"></i>
        <% end %>

      <% end %>

      <%= link_to "Delete", weblink_path(link), :method => :delete %>
      <%= link_to "Update", edit_weblink_path(link), :method => :patch %>
      </div>
      </h5>
      <h5 class="link-url"><a href=""><%= link.url.slice!(/[^http:\/\/www\.].+(.com)/) %></a></h5>

      </li>
    </ul>
  
<!-- </div> -->
  <% end %><br>
</div>    


<!--------------- Drop down test -------------->



<!-- <li id="pagenav_options">
  <a title="" href="#">
  <span class="nav-username">Leah</span>
  <span class="nav-downnotch"></span></a>
<div id="pagenav_options_container" class="dropSelector innerpopover-active" style>
    <a>
      </a>
<div class="popover-new popover-new-bottomleft popover-active" style="top: 23px; left: -180.000049591065px;"><div class="popover-new-header">
    <a class="popover-new-close" href="#"></a>
    </div>
<div class="arrow"></div><ul class="popover-new-list">
  <li class="popover-new-listitem premium" val="premium">
    <a href="#">Premium<span class="nav-icon"></span>
     </a>
    </li>
<li class="popover-new-listitem help" val="help">
  <a href="#">Help<span class="nav-icon"></span>
    </a>
</li>
  <li class="popover-new-listitem options" val="options">
<a href="#">Options<span class="nav-icon"></span></a>
    </li>
<li class="popover-new-listitem logout last" val="logout">
  <a href="#">Logout<span class="nav-icon"></span>
    </a>
    </li>
    </ul>
  </div>
  </div>
</li>
 -->

<!-- <table>
  
  <tr>
    <td>

  <nav id="navigation" class="site-navigation" role="navigation">
  <ul class="menu">
    <li class="menu-item"><a href="#">News</a></li>
    <li class="menu-item"><a href="#">Snippets</a>
      <ul class="dropdown">
        <li class="menu-item sub-menu"><a href="#">CSS</a></li>
        <li class="menu-item sub-menu"><a href="#">HTML</a></li>
        <li class="menu-item sub-menu"><a href="#">jQuery</a></li>
        <li class="menu-item sub-menu"><a href="#">PHP</a></li>
        <li class="menu-item sub-menu"><a href="#">WordPress</a></li>
      </ul>
    </li>
    <li class="menu-item"><a href="#">Inspiration</a></li>
    <li class="menu-item"><a href="#">Tools</a></li>
    <li class="menu-item"><a href="#">Tutorials</a></li>
  </ul>
</nav>

    </td>
 </tr>

</table> -->

app/views/weblinks/new.html.erb
<h1>Weblinks#new</h1>

You are signed in <%= current_user.name %> | <%= link_to 'Logout', '/logout' %><br>
<%= notice %><br>
You can add links -- 
<%= render 'addlinks' %><br>

<%= link_to 'My links', '/mylinks' %><br>
<%= link_to 'Home', '/' %><br>

app/views/weblinks/show.html.erb
<nav>
  <div class="show-page-nav">
    <%= link_to mylinks_path, method: :get do%>
      <i class="fa fa-arrow-left fa-2x"></i>
    <% end %>&nbsp;
    <%= link_to weblink_path, :method => :delete do %>
      <i class="fa fa-trash fa-2x"></i>
    <% end %>&nbsp;

     <% if @url_id.favorited? %>
            <%= link_to unfavorite_weblink_path, method: :patch do %>
              <i style="opacity: 0.4;" class="fa fa-heart fa-2x"></i>
            <% end %>
      <% else %>
        <%= link_to favorite_weblink_path, method: :patch do %>
          <i class="fa fa-heart-o fa-2x"></i>
        <% end %>

      <% end %>

  </div>
</nav>


<div class="reader-content">
  <h1 class="doctitle"><%= @doc.title %></h1><br>
    <div class="subinfo">
      <h5 class="author"><%= @doc.author %>, <a href="<%= @url_id.url %>"><%= @url_id.url.slice!(/[^http:\/\/www\.].+(.com)/) %></a>

      <a class="original" href="<%= @url_id.url %>">View Original</a></h5>
    </div>
  <h4><%= @doc.body %></h4>
<%# binding.pry %>
</div>